# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(max_length=20)),
                ('connector_name', models.CharField(max_length=200)),
                ('connector_status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('device_name', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.AddField(
            model_name='connector',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviceManager.Device'),
        ),
    ]
